service: quno-backend-challenge

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

custom:
  resourceRoutes: true

plugins:
  - serverless-offline

functions:
  doctors:
    name: get-doctors
    handler: dist/lambdas/doctors.handler
    memorySize: 128
    timeout: 10
    environment:
    events:
      - http:
          path: /doctors/{id}
          method: GET
          cors: true
      - http:
          path: /doctors
          method: GET
          cors: true
      - http:
          path: /doctors
          method: POST
          cors: true